image: weyforth/drone-docker
env:
  - LOG=file
script:
  - tools/pre_deploy
branches:
  - master
notify:
  email:
    recipients:
      - build@mikefarrow.co.uk
deploy:
  bash:
    script:
      - ssh deploy@46.101.22.223 'rm -rf app-build'
      - scp -o StrictHostKeyChecking=no -P 22 -r . deploy@46.101.22.223:app-build/
      - ssh deploy@46.101.22.223 app-build/tools/deploy
    when:
      branch: master
