title: Paul Schütze Perfume
source: ./_site
destination: ./dist
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - disable_indented_code_blocks
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - autolink
    - tables
    - footnotes
highlighter: rouge
permalink: pretty
array: []
include:
  - _assets
exclude:
  - _assets/scss
ga_tracking_id: UA-68744000-1