#!/bin/bash

source app-build/tools/_functions

set -e

export COMPOSE_FILE="docker-compose-production.yml"

cd app-build

heading "Pulling Docker images"
docker-compose pull >/dev/null

cd ../

if [[ -d app ]]; then
	cd app
	tools/stop production
	cd ../
fi

heading "Copying files"
rm -rf app && cp -r app-build app && echo "done"

cd app
tools/start production

echo ""
